<a href="https://colab.research.google.com/github/emineherkci/-dev/blob/main/veribilimi_%C3%B6dev7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
#1. ödev
import numpy as np
dizi = np.array([3, 7, 10, 5, 2, 8], dtype=int)
print("Dizi:", dizi)
print("Boyut (ndim):", dizi.ndim)
print("Eleman sayısı (size):", dizi.size)
print("Şekli (shape):", dizi.shape)



Dizi: [ 3  7 10  5  2  8]
Boyut (ndim): 1
Eleman sayısı (size): 6
Şekli (shape): (6,)


In [27]:
#2. ödev
import numpy as np
iki_boyutlu = np.array([[1, 2, 6, 7],
                        [4, 3, 9, 5]])
print("İki Boyutlu Dizi:\n", iki_boyutlu)
print("Boyut (ndim):", iki_boyutlu.ndim)
print("Eleman Sayısı (size):", iki_boyutlu.size)
print("Şekli (shape):", iki_boyutlu.shape)
print("Satır Sayısı:", iki_boyutlu.shape[0])
print("Sütun Sayısı:", iki_boyutlu.shape[1])
uc_boyutlu = np.array([[[7, 5, 14], [21, 8, 11]],
                       [[8, 6, 20], [14, 3, 9]]])
print("\nÜç Boyutlu Dizi:\n", uc_boyutlu)
print("Boyut (ndim):", uc_boyutlu.ndim)
print("Eleman Sayısı (size):", uc_boyutlu.size)
print("Şekli (shape):", uc_boyutlu.shape)
print("Katman Sayısı:", uc_boyutlu.shape[0])
print("Satır Sayısı (her katmanda):", uc_boyutlu.shape[1])
print("Sütun Sayısı (her satırda):", uc_boyutlu.shape[2])


İki Boyutlu Dizi:
 [[1 2 6 7]
 [4 3 9 5]]
Boyut (ndim): 2
Eleman Sayısı (size): 8
Şekli (shape): (2, 4)
Satır Sayısı: 2
Sütun Sayısı: 4

Üç Boyutlu Dizi:
 [[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut (ndim): 3
Eleman Sayısı (size): 12
Şekli (shape): (2, 2, 3)
Katman Sayısı: 2
Satır Sayısı (her katmanda): 2
Sütun Sayısı (her satırda): 3


In [28]:
#3. ödev
iki_boyutlu = np.array([[1, 2, 6, 7],
                        [4, 3, 9, 5]])
print("2 elemanı:", iki_boyutlu[0, 1])
print("7 elemanı:", iki_boyutlu[0, 3])
uc_boyutlu = np.array([[[7, 5, 14],
                        [21, 8, 11]],

                       [[8, 6, 20],
                        [14, 3, 9]]])
print("9 elemanı:", uc_boyutlu[1, 1, 2])
print("5 elemanı:", uc_boyutlu[0, 0, 1])


2 elemanı: 2
7 elemanı: 7
9 elemanı: 9
5 elemanı: 5


In [29]:
# 4. ödev
import numpy as np

# İki boyutlu array
iki_boyutlu = np.array([[1, 2, 6, 7],
                        [4, 3, 9, 5]])

# Üç boyutlu array
uc_boyutlu = np.array([[[7, 5, 14],
                        [21, 8, 11]],

                       [[8, 6, 20],
                        [14, 3, 9]]])

# Slicing işlemleri
print("İki boyutlu arraydeki 2 ve 6:", iki_boyutlu[0, 1:3])
print("İki boyutlu arraydeki 3, 9, 5:", iki_boyutlu[1, 1:])
print("Üç boyutlu arraydeki 21, 8, 11:", uc_boyutlu[0, 1, :])
print("Üç boyutlu arraydeki 6, 20:", uc_boyutlu[1, 0, 1:3])


İki boyutlu arraydeki 2 ve 6: [2 6]
İki boyutlu arraydeki 3, 9, 5: [3 9 5]
Üç boyutlu arraydeki 21, 8, 11: [21  8 11]
Üç boyutlu arraydeki 6, 20: [ 6 20]


In [30]:
# 5. ödev
import numpy as np

# 5 satır 3 sütunluk sıfırlardan oluşan array
sifirlar = np.zeros((5, 3), dtype=int)

# 5 satır 3 sütunluk birlerden oluşan array
birler = np.ones((5, 3), dtype=int)

# Satır bazında birleştirme (alt alta ekleme)
satir_birlesim = np.vstack((sifirlar, birler))

# Sütun bazında birleştirme (yan yana ekleme)
sutun_birlesim = np.hstack((sifirlar, birler))

# Sonuçları yazdıralım
print("Sıfırlardan oluşan dizi:\n", sifirlar)
print("\nBirlerden oluşan dizi:\n", birler)
print("\nSatır bazında birleştirme:\n", satir_birlesim)
print("\nSütun bazında birleştirme:\n", sutun_birlesim)


Sıfırlardan oluşan dizi:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Birlerden oluşan dizi:
 [[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Satır bazında birleştirme:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

Sütun bazında birleştirme:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
